repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-json

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        args: [--line-length=78]

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: [--profile=black, --line-length=78]

-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
    -   id: nbqa-isort
        args: [--profile=black, --line-length=78]
    -   id: nbqa-black
        args: [--line-length=78]

-   repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
    -   id: nbstripout
