# price is dollar per token
anthropic.claude-instant-v1:
  price_in: 8.0e-7
  price_out: 2.4e-6
  short_name: instant
anthropic.claude-v2:1:
  price_in: 8.0e-6
  price_out: 2.4e-5
  short_name: claudev2
anthropic.claude-3-sonnet-20240229-v1:0:
  price_in: 3.0e-6
  price_out: 1.5e-5
  short_name: sonnet
anthropic.claude-3-haiku-20240307-v1:0:
  price_in: 2.5e-7
  price_out: 1.25e-6
  short_name: haiku
openai.gpt-3.5-turbo-0613:
  price_in: 1.5e-6
  price_out: 2.0e-6
  short_name: gpt35
mistral.mistral-large-2402-v1:0:
  price_in: 8.0e-6
  price_out: 2.4e-5
  short_name: mistralL
mistral.mistral-small-2402-v1:0:
  price_in: 1.0e-6
  price_out: 3.0e-6
  short_name: mistralS
meta.llama3-70b-instruct-v1:0:
  price_in: 2.65e-6
  price_out: 3.5e-6
  short_name: llama
us.amazon.nova-micro-v1:0:
  price_in: 3.5e-8
  price_out: 1.4e-7
  short_name: nova-micro
us.amazon.nova-lite-v1:0:
  price_in: 6.0e-8
  price_out:  2.4e-7
  short_name: nova-lite
us.amazon.nova-pro-v1:
  price_in: 8.0e-7
  price_out:  3.2e-7
  short_name: nova-pro
